#!/usr/bin/env node
var diff = require('./')
var fs = require('fs')

if (process.argv.length < 4) {
  process.stderr.write('Usage: <a.json> <b.json>\n')
  process.exit(1) }

process.stdout.write(
  diff(
    JSON.parse(fs.readFileSync(process.argv[2], 'utf8')),
    JSON.parse(fs.readFileSync(process.argv[3], 'utf8'))) +
  '\n')
